[build]
filehash = true
# Set the output directory for the web build.
dist = "target/trunk"
# This is needed in order to host the game on itch.io.
# https://github.com/trunk-rs/trunk/issues/395#issuecomment-1474829618
public_url = "./"
